import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import * as api from "./api/api.js";
import CustomizedDialogs from "@/components/formDialog.js";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState([]);

  // const getData = () => {
  //   api.getUsers().then((users) => {
  //     setData(users.data);
  //     console.log(users.data);
  //   })
  // }

  // useEffect(getData, []);

  return (
    <>
    <Head>
        <title>BruinShare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <CustomizedDialogs/>

      
    </>
  );
}
